name: Mintlify Broken Links Check

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:
  check-links:
    name: Check Mintlify Broken Links
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libsecret-1-dev

      - name: Install Mintlify CLI
        run: npm install -g mintlify

      - name: Run Broken Links Checker
        run: mintlify broken-links